version: '3.4'
services:
  alfresco-sync-share:
    image: alfresco-share-alfresco-sync:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-sync-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: alfresco-sync-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  alfresco-sync-acs:
    image: alfresco-content-services-alfresco-sync:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../alfresco-sync-platform-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    command: ["catalina.sh", "run"]
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-sync-acs-volume:/usr/local/tomcat/alf_data
      - ../../../alfresco-sync-platform/target/classes:/usr/local/tomcat/hotswap-agent/alfresco-sync-platform/target/classes
      - ../../../alfresco-sync-integration-tests/target/test-classes:/usr/local/tomcat/hotswap-agent/alfresco-sync-integration-tests/target/test-classes
    depends_on:
      - alfresco-sync-postgres
  alfresco-sync-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-sync-db-volume:/var/lib/postgresql/data
  alfresco-sync-ass:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      SOLR_ALFRESCO_HOST: alfresco-sync-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-sync-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
    ports:
      - "8983:8983"
    volumes:
      - alfresco-sync-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-sync-ass-volume:/opt/alfresco-search-services/data
volumes:
  alfresco-sync-acs-volume:
    external: true
  alfresco-sync-db-volume:
    external: true
  alfresco-sync-ass-volume:
    external: true
